Repository oncokb/oncokb-transcript, pull requests merged in 2024-08, with the labels that each got.

#414 Tagging release on sentry
  .github/workflows/docker-release.yml
Labels: devops

#419 Minor updates
  pom.xml
  src/main/java/org/mskcc/oncokb/curation/service/EnsemblService.java
  src/main/java/org/mskcc/oncokb/curation/service/dto/pubmed/PubMedDTO.java
  src/main/java/org/mskcc/oncokb/curation/service/mapper/PubMedMapper.java
  src/main/java/org/mskcc/oncokb/curation/util/GsonUtils.java
Labels: fix

#417 Do not show needs curation for categorical alterations
  src/main/webapp/app/shared/badge/NotCuratableBadge.tsx
Labels: fix

#421 Report all exceptions to setnry
  pom.xml
  src/main/java/org/mskcc/oncokb/curation/OncokbCurationApp.java
  src/main/resources/config/application-dev.yml
  src/main/resources/config/application-prod.yml
Labels: devops

#420 Remove uuid from meta when newly created tumor has been deleted
  src/main/webapp/app/pages/curation/collapsible/CancerTypeCollapsible.tsx
  src/main/webapp/app/service/firebase/firebase-gene-service.ts
  src/main/webapp/app/service/firebase/firebase-meta-service.spec.ts
  src/main/webapp/app/service/firebase/firebase-meta-service.ts
  src/main/webapp/app/shared/util/firebase/firebase-review-utils.tsx
Labels: fix

#422 Parse comma seperated alterations and add info icon to add mutation modal input
  src/main/webapp/app/app.scss
  src/main/webapp/app/components/sidebar/NavigationSidebar.tsx
  src/main/webapp/app/shared/modal/AddMutationModal.tsx
  src/main/webapp/app/shared/util/utils.spec.ts
  src/main/webapp/app/shared/util/utils.tsx
  src/test/javascript/screenshots/baseline/desktop_chrome/add-mutation-modal--1920x1080.png
Labels: enhancement

#423 Use treatment valuePath when generating review for excludedRCTs
  src/main/webapp/app/shared/util/firebase/firebase-review-utils.spec.ts
  src/main/webapp/app/shared/util/firebase/firebase-review-utils.tsx
Labels: fix

#424 Handle when Instant json element is a json object
  src/main/java/org/mskcc/oncokb/curation/config/InstantTypeAdapter.java
Labels: fix

#427 Textarea in review mode should fit text content
  src/main/webapp/app/shared/firebase/input/RealtimeBasicInput.tsx
  src/main/webapp/app/shared/firebase/input/styles.module.scss
  src/test/javascript/screenshots/baseline/desktop_chrome/new-mutation-review-collapsible--1920x1080.png
  src/test/javascript/screenshots/baseline/desktop_chrome/open-therapy-collapsible--1920x1080.png
  src/test/javascript/screenshots/baseline/desktop_chrome/review-page--1920x1080.png
  src/test/javascript/screenshots/baseline/desktop_chrome/updated-gene-summary-review-collapsible--1920x1080.png
Labels: enhancement

#428 Fix reject cancer type name review
  src/main/webapp/app/service/firebase/firebase-gene-review-service.spec.ts
  src/main/webapp/app/service/firebase/firebase-gene-review-service.ts
Labels: fix

#432 Add reference to oncokb sop alteration nomenclature in add mutation modal helper
  src/main/webapp/app/shared/links/SopPageLink.tsx
  src/main/webapp/app/shared/modal/AddMutationModal.tsx
Labels: enhancement
