Repository oncokb/oncokb-transcript, pull requests merged in 2024-11, with the labels that each got.

#469 Create gene on gene link click if does not exist
  src/main/webapp/app/pages/curation/GeneListPage.tsx
  src/main/webapp/app/pages/curation/button/SomaticGermlineToggleButton.tsx
  src/main/webapp/app/shared/util/firebase/firebase-utils.tsx
Labels: fix

#470 Gene header redesign
  package.json
  src/main/webapp/app/components/tabs/CurationToolsTab.tsx
  src/main/webapp/app/components/tabs/GeneListPageToolsTab.tsx
  src/main/webapp/app/components/tabs/ReviewHistoryTab.tsx
  src/main/webapp/app/oncokb-commons/components/texts/GeneAliasesDescription.tsx
  src/main/webapp/app/pages/curation/BadgeGroup.tsx
  src/main/webapp/app/pages/curation/CurationPage.tsx
  src/main/webapp/app/pages/curation/GeneListPage.tsx
  src/main/webapp/app/pages/curation/collapsible/ReviewCollapsible.tsx
  src/main/webapp/app/pages/curation/geneticTypeTabs/GeneticTypeTabs.tsx
  src/main/webapp/app/pages/curation/geneticTypeTabs/genetic-type-tabs.module.scss
  src/main/webapp/app/pages/curation/geneticTypeTag.tsx/GeneticTypeTag.tsx
  src/main/webapp/app/pages/curation/geneticTypeTag.tsx/genetic-type-tag.module.scss
  src/main/webapp/app/pages/curation/header/GeneHeader.tsx
  src/main/webapp/app/pages/curation/header/GeneticTypeTabHeader.tsx
  src/main/webapp/app/pages/curation/review/ReviewPage.tsx
  src/main/webapp/app/service/firebase/firebase-gene-service.ts
  src/main/webapp/app/shared/badge/DefaultBadge.tsx
  src/main/webapp/app/shared/badge/NoEntryBadge.tsx
  src/main/webapp/app/shared/badge/NotCuratableBadge.tsx
  src/main/webapp/app/shared/icons/ExternalLinkIcon.tsx
  src/main/webapp/app/shared/icons/external-link-icon.module.scss
  src/main/webapp/app/shared/links/EnsemblIdLinkout.tsx
  src/main/webapp/app/shared/links/HgncLink.tsx
  src/main/webapp/app/shared/links/PubmedGeneArticlesLink.tsx
  src/main/webapp/app/shared/links/PubmedGeneLink.tsx
  src/main/webapp/app/shared/links/RefSeqLinkout.tsx
  src/main/webapp/app/shared/modal/RelevantCancerTypesModal.tsx
  src/main/webapp/app/shared/table/GenomicIndicatorsTable.tsx
  src/main/webapp/app/shared/table/VusTable.tsx
  src/main/webapp/app/shared/text/EnsemblIdText.tsx
  src/main/webapp/app/shared/text/RefSeqText.tsx
  src/main/webapp/app/shared/text/TimeAgoText.tsx
  src/main/webapp/app/shared/util/entity-utils/gene-entity-utils.ts
  src/main/webapp/app/stores/router.store.ts
  src/main/webapp/app/variables.scss
  src/test/javascript/screenshots/baseline/desktop_chrome/add-mutation-modal--1920x1080.png
  src/test/javascript/screenshots/baseline/desktop_chrome/mutation-collapsible--1920x1080.png
  src/test/javascript/screenshots/baseline/desktop_chrome/open-therapy-collapsible--1920x1080.png
  src/test/javascript/screenshots/baseline/desktop_chrome/relevant-cancer-types-modal--1920x1080.png
  src/test/javascript/screenshots/baseline/desktop_chrome/review-page--1920x1080.png
  src/test/javascript/screenshots/baseline/desktop_chrome/vus-table--1920x1080.png
  src/test/javascript/spec/data-import.e2e.ts
  src/test/javascript/spec/e2e.ts
  src/test/javascript/spec/screenshot.ts
  webpack/webpack.common.js
  yarn.lock
Labels: feature

#473 Parse slash in mutation name
  src/main/webapp/app/shared/modal/AddMutationModal.tsx
Labels: fix

#476 Added synonyms to Drugs Endpoint
  src/main/java/org/mskcc/oncokb/curation/repository/DrugRepository.java
Labels: enhancement

#475 Align germline color scheme with public website
  src/main/webapp/app/config/colors.ts
  src/main/webapp/app/pages/curation/button/SomaticGermlineToggleButton.tsx
  src/main/webapp/app/variables.scss
  src/test/javascript/spec/e2e.ts
Labels: enhancement

#478 Allow user to unlock review mode
  src/main/webapp/app/pages/curation/header/GeneticTypeTabHeader.tsx
Labels: fix

#477 Fix transcript edit page
  src/main/webapp/app/entities/transcript/transcript-update.tsx
  src/main/webapp/app/shared/select/EnsemblGeneSelect.tsx
Labels: fix

#479 Check against undefined array items for core submissions
  src/main/webapp/app/service/firebase/firebase-gene-review-service.ts
  src/main/webapp/app/shared/util/core-evidence-submission/core-evidence-submission-utils.ts
Labels: fix

#480 Add keycloak idp mapper for picture attribute
  src/main/docker/realm-config/oncokb-curation-realm.json
  src/main/resources/config/application.yml
Labels: fix
