Repository oncokb/oncokb-transcript, pull requests merged in 2024-09, with the labels that each got.

#435 Fix drug code not selectable
  src/main/webapp/app/entities/drug/drug-update.tsx
Labels: fix

#434 Avoid fetching management info repeatedly
  src/main/webapp/app/app.tsx
  src/main/webapp/app/components/sidebar/NavigationSidebar.tsx
  src/main/webapp/app/stores/management.store.ts
Labels: fix

#438 Bump actions to latest version
  .github/workflows/after-branch-commit.yml
  .github/workflows/docker-release.yml
  .github/workflows/github-ci.yml
  .github/workflows/webdriver-test.yml
Labels: dependencies

#443 Add mutations sorting by firebase index
  src/main/webapp/app/pages/curation/header/MutationsSectionHeader.tsx
Labels: enhancement

#444 Delete mutation/tumor/treatment as last step to avoid stale index
  src/main/webapp/app/pages/curation/review/ReviewPage.tsx
  src/main/webapp/app/service/firebase/firebase-gene-review-service.ts
  src/main/webapp/app/shared/util/firebase/firebase-path-utils.spec.ts
  src/main/webapp/app/shared/util/firebase/firebase-path-utils.ts
Labels: fix

#445 Change searchEntities to readHandler instead of updateHandler
  src/main/webapp/app/shared/util/pagination-crud-store.ts
Labels: fix

#433 Allow curating mutation summary
  src/main/webapp/app/pages/curation/collapsible/CancerTypeCollapsible.tsx
  src/main/webapp/app/pages/curation/collapsible/MutationCollapsible.tsx
  src/main/webapp/app/shared/firebase/input/RealtimeBasicInput.tsx
  src/main/webapp/app/shared/firebase/input/RealtimeInputs.tsx
  src/main/webapp/app/shared/model/firebase/firebase.model.ts
  src/main/webapp/app/shared/util/firebase/firebase-utils.tsx
  src/test/javascript/screenshots/baseline/desktop_chrome/mutation-effect-not-curatable--1920x1080.png
  src/test/javascript/screenshots/baseline/desktop_chrome/open-therapy-collapsible--1920x1080.png
  src/test/javascript/screenshots/baseline/desktop_chrome/relevant-cancer-types-modal--1920x1080.png
Labels: feature

#441 Parse protein change case insensitive
  src/main/java/org/mskcc/oncokb/curation/service/MainService.java
  src/main/java/org/mskcc/oncokb/curation/util/AlterationUtils.java
  src/main/java/org/mskcc/oncokb/curation/util/parser/ParsingStatus.java
  src/main/java/org/mskcc/oncokb/curation/util/parser/ProteinChangeParser.java
  src/test/java/org/mskcc/oncokb/curation/test/AlterationUtilsTest.java
  src/test/java/org/mskcc/oncokb/curation/test/ParseProteinChangeParameterizedTest.java
  src/test/resources/data/test_parse_protein_change.csv
Labels: enhancement

#450 Fix adding CDx biomarker association
  src/main/webapp/app/components/panels/CompanionDiagnosticDevicePanel.tsx
  src/main/webapp/app/entities/companion-diagnostic-device/companion-diagnostic-device-update.tsx
  src/main/webapp/app/entities/companion-diagnostic-device/companion-diagnostic-device.tsx
  src/main/webapp/app/shared/select/AlterationSelect.tsx
  src/main/webapp/app/shared/select/CancerTypeSelect.tsx
  src/main/webapp/app/shared/select/DrugSelect.tsx
  src/main/webapp/app/shared/select/FdaSubmissionSelect.tsx
  src/main/webapp/app/shared/select/GeneSelect.tsx
  src/test/javascript/screenshots/baseline/desktop_chrome/add-therapy-modal--1920x1080.png
Labels: fix
